/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passwordgenerator.apresentacao;

import java.awt.Toolkit;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.Transferable;
import passwordgenerator.suporte.Formatacao;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;

/**
 *
 * @author vitor
 */
public class FrmGeraSenha extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FrmGeraSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGeradorDeSenha = new javax.swing.JLabel();
        pnlInfoSenha = new javax.swing.JPanel();
        tfdSenha = new javax.swing.JTextField();
        spnTamSenha = new javax.swing.JSpinner(new SpinnerNumberModel(99, 1, 99, 1));
        btnGeararSenha = new javax.swing.JButton();
        tfdCrcEspeciais = new javax.swing.JTextField();
        lblNumCaracteres = new javax.swing.JLabel();
        lblCrcEspeciais = new javax.swing.JLabel();
        btnCopiarSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador de Senha");
        setResizable(false);

        lblGeradorDeSenha.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblGeradorDeSenha.setText("Gerador de Senha");

        pnlInfoSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tfdSenha.setEditable(false);
        tfdSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        spnTamSenha.setEditor(new JSpinner.NumberEditor(this.spnTamSenha, "##"));

        btnGeararSenha.setText("Gerar Senha");
        btnGeararSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeararSenhaActionPerformed(evt);
            }
        });

        tfdCrcEspeciais.setDocument(new Formatacao());
        tfdCrcEspeciais.setText(" =!^#&_@%+-?*|${}[]()/\\'\"`~,;:.<>");

        lblNumCaracteres.setText("Número de Caracteres");

        lblCrcEspeciais.setText("Caracteres Especiais");

        btnCopiarSenha.setText("Copiar Senha");
        btnCopiarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInfoSenhaLayout = new javax.swing.GroupLayout(pnlInfoSenha);
        pnlInfoSenha.setLayout(pnlInfoSenhaLayout);
        pnlInfoSenhaLayout.setHorizontalGroup(
            pnlInfoSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoSenhaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlInfoSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlInfoSenhaLayout.createSequentialGroup()
                        .addComponent(btnGeararSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCopiarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoSenhaLayout.createSequentialGroup()
                        .addComponent(tfdCrcEspeciais, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCrcEspeciais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlInfoSenhaLayout.createSequentialGroup()
                        .addComponent(spnTamSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumCaracteres))
                    .addComponent(tfdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        pnlInfoSenhaLayout.setVerticalGroup(
            pnlInfoSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoSenhaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tfdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(pnlInfoSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnTamSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumCaracteres))
                .addGap(10, 10, 10)
                .addGroup(pnlInfoSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdCrcEspeciais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCrcEspeciais))
                .addGap(20, 20, 20)
                .addGroup(pnlInfoSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCopiarSenha)
                    .addComponent(btnGeararSenha))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        spnTamSenha.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGeradorDeSenha)
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pnlInfoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblGeradorDeSenha)
                .addGap(25, 25, 25)
                .addComponent(pnlInfoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeararSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeararSenhaActionPerformed

        String caracteres = " =!^#&_@%+-?*|${}[]()/\\'\"`~,;:.<>";
        String crctrsRemovidos = "";

        for (int i = 0; i < caracteres.length(); i++) {
            if (!tfdCrcEspeciais.getText().contains(String.valueOf(caracteres.charAt(i)))) {
                if (String.valueOf(caracteres.charAt(i)).matches("[\\^\\-\\[\\]\\\\]")) {
                    crctrsRemovidos = crctrsRemovidos + "\\" + String.valueOf(caracteres.charAt(i));
                } else {
                    crctrsRemovidos = crctrsRemovidos + String.valueOf(caracteres.charAt(i));
                }
            }
        }

        String senha = "";
        int valor;

        while (spnTamSenha.getValue().hashCode() > senha.length()) {
            valor = (int) (32 + Math.random() * (126 - 31));
            if (!crctrsRemovidos.isEmpty()) {
                if (!String.valueOf((char) valor).matches("[" + crctrsRemovidos + "]")) {
                    senha += (char) valor;
                }
            } else {
                senha += (char) valor;
            }
        }
        tfdSenha.setText(senha);
    }//GEN-LAST:event_btnGeararSenhaActionPerformed

    private void btnCopiarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarSenhaActionPerformed
        tfdSenha.requestFocus();
        tfdSenha.selectAll();
        Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
        ClipboardOwner selecao = new StringSelection(tfdSenha.getText());
        board.setContents((Transferable) selecao, selecao);
    }//GEN-LAST:event_btnCopiarSenhaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopiarSenha;
    private javax.swing.JButton btnGeararSenha;
    private javax.swing.JLabel lblCrcEspeciais;
    private javax.swing.JLabel lblGeradorDeSenha;
    private javax.swing.JLabel lblNumCaracteres;
    private javax.swing.JPanel pnlInfoSenha;
    private javax.swing.JSpinner spnTamSenha;
    private javax.swing.JTextField tfdCrcEspeciais;
    private javax.swing.JTextField tfdSenha;
    // End of variables declaration//GEN-END:variables
}
